### ISSUE TITLE
MCP Unity 1.3.0 fails to compile on Unity 6000.5.0b8

### ISSUE THREAD

**Issue by JOY** [CoderGamester/mcp-unity#137]
### Environment

- Unity version: 6000.5.0b8
- OS: Windows
- Package installed via Unity Package Manager Git URL:
  `https://github.com/CoderGamester/mcp-unity.git`
- Resolved package:
  `com.gamelovers.mcp-unity`
- Resolved version:
  `1.3.0`

### What happened

The package installs successfully. Initially the import appeared quiet, but after `AssetDatabase.Refresh()` Unity compilation failed on Unity 6000.5.0b8.

Unity reports `CS0619` errors because several APIs used by the package are obsolete in this Unity version and are treated as compile errors.

### Example failing files

```text
Library\PackageCache\com.gamelovers.mcp-unity@a32e47d4ec87\Editor\Tools\GameObjectTools.cs
Library\PackageCache\com.gamelovers.mcp-unity@a32e47d4ec87\Editor\Resources\GetGameObjectResource.cs
Library\PackageCache\com.gamelovers.mcp-unity@a32e47d4ec87\Editor\Tools\UpdateGameObjectTool.cs
Library\PackageCache\com.gamelovers.mcp-unity@a32e47d4ec87\Editor\Tools\TransformTools.cs
```

### Example errors

```text
error CS0619: 'EditorUtility.InstanceIDToObject(int)' is obsolete: 'InstanceIDToObject(int) is obsolete. Use EditorUtility.EntityIdToObject instead.'

error CS0619: 'Object.GetInstanceID()' is obsolete: 'GetInstanceID is deprecated. Use GetEntityId instead. This will be removed in a future version.'
```

### Affected APIs

The package appears to use older instance ID APIs in multiple files:

- `Object.GetInstanceID()`
- `EditorUtility.InstanceIDToObject(int)`

Unity 6000.5 suggests replacing them with:

- `GetEntityId`
- `EditorUtility.EntityIdToObject`

### Expected behavior

The package should compile cleanly on current Unity 6 beta versions, especially Unity 6000.5.x.

### Actual behavior

Compilation fails, which prevents testing the WebSocket bridge on port 8090 and runtime MCP tools.

### Notes

I removed the package after the compile failure to restore the project to a clean state.

**Comment by CoderGamester** [comment]
Thank you for the report @JOY 

Currently this MCP does not support the beta and alpha versions of Unity.
I will update to support 6.5 as soon is global released

**Comment by dtinth** [comment]
[Unity 6.5 is here (6000.5.0f1)](https://unity.com/releases/editor/whats-new/6000.5.0f1)

**Comment by The-prof** [comment]
any update on the fix

**Comment by CoderGamester** [comment]
Apologies, I am traveling now for work and will look into this ASAP
My ETA is next week when I am back on my computer, but I will try to squeeze something in the meantime

**Comment by CoderGamester** [comment]
Fixed in c80105e, now pushed to main.

@JOY @dtinth @The-prof this should resolve the Unity 6000.5 / Unity 6.3+ compile failures. The fix replaces the obsolete InstanceID APIs with an asmdef-scoped Unity 6000.3+ EntityId path, updates shader property inspection away from obsolete ShaderUtil APIs, and reduces MCP Unity console noise so the console stays clean after reload.

Validated locally against Unity 6000.5.2f1:
- Unity C# compile passes
- Unity Console reports 0 errors and 0 warnings
- Server build passes
- Server tests pass: 10 suites / 112 tests
